// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACV-Mc6iEAsUbn_uK04aXUQmu-gG_Lcvk',
    appId: '1:149991281969:web:2615aea28007ddde9a4c10',
    messagingSenderId: '149991281969',
    projectId: 'e-kart-a11a0',
    authDomain: 'e-kart-a11a0.firebaseapp.com',
    storageBucket: 'e-kart-a11a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwPm6MuSZ4kjzxgDoDvTqGHpfwLc8zztU',
    appId: '1:149991281969:android:a247583d9aa17cdf9a4c10',
    messagingSenderId: '149991281969',
    projectId: 'e-kart-a11a0',
    storageBucket: 'e-kart-a11a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJStJDD92pZQ5YJSLm9CqHqIkmFr3s1bM',
    appId: '1:149991281969:ios:53dd42428f6f11d49a4c10',
    messagingSenderId: '149991281969',
    projectId: 'e-kart-a11a0',
    storageBucket: 'e-kart-a11a0.appspot.com',
    androidClientId: '149991281969-aia7oa6rfrb64pcaqv709vo3ln9qfkoo.apps.googleusercontent.com',
    iosClientId: '149991281969-4bj9p51fi90g891squelmm3q5ilvka80.apps.googleusercontent.com',
    iosBundleId: 'com.jamshi.eCartShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJStJDD92pZQ5YJSLm9CqHqIkmFr3s1bM',
    appId: '1:149991281969:ios:53dd42428f6f11d49a4c10',
    messagingSenderId: '149991281969',
    projectId: 'e-kart-a11a0',
    storageBucket: 'e-kart-a11a0.appspot.com',
    androidClientId: '149991281969-aia7oa6rfrb64pcaqv709vo3ln9qfkoo.apps.googleusercontent.com',
    iosClientId: '149991281969-4bj9p51fi90g891squelmm3q5ilvka80.apps.googleusercontent.com',
    iosBundleId: 'com.jamshi.eCartShopping',
  );
}
